package com.creatorconnect.entity.enums;

public enum NotificationType {
    APPLICATION_RECEIVED,
    APPLICATION_ACCEPTED,
    APPLICATION_REJECTED,
    APPLICATION_SHORTLISTED,
    SUBMISSION_UPLOADED,
    SUBMISSION_APPROVED,
    SUBMISSION_REJECTED,
    PAYMENT_RELEASED,
    CAMPAIGN_CLOSED,
    ACCOUNT_VERIFIED,
    SYSTEM_ALERT
}
